name: Python Tests with Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.18.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      # Step 4: Build and run tests with Docker Compose
      - name: Build and Run Tests with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build --abort-on-container-exit --exit-code-from python bin/test

      # Step 5: Clean up containers (optional)
      - name: Clean up
        run: |
          docker-compose down
